name: apps-annia
channels:
  - conda-forge
  - defaults
dependencies:
  # Base
  - python=3.9.*              # 3.9 es estable y compatible con todo lo tuyo
  - pip
  - tk                        # Tk/Tcl para Tkinter (en conda, no pip)
  - numpy>=1.21,<2.0
  - matplotlib>=3.4,<3.8
  - pillow>=8,<11
  - certifi
  - ca-certificates
  - openssl
  - setuptools
  - wheel
  - sqlite
  - zlib
  # Pip-only (sin duplicar numpy/matplotlib)
  - pip:
      - ttkthemes>=3.2.0
      - pygubu==0.18
      - pygubu-designer==0.22
      - appdirs>=1.4.4
      - altgraph>=0.17
      - mako>=1.1
      - markupsafe>=2.0
      - python-dateutil>=2.8
      - six>=1.16
      - importlib-metadata>=4.8; python_version < "3.10"
      - typing-extensions>=4.0; python_version < "3.11"
      - zipp>=3.6; python_version < "3.10"
      - pywin32-ctypes==0.2.0; platform_system == "Windows"

